apiVersion: v1
kind: Service
metadata:
  name: python-microservice
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /users  
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: python-microservice
  ports:
    - port: 80
      targetPort: 5000
      name: http
