apiVersion: v1
kind: Service
metadata:
  name: python-microservice
spec:
  type: NodePort
  selector:
    app: python-microservice
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30555
